#!/usr/bin/env python
import os
import sys
import re

os.system('pylint --rcfile=pylintrc '+sys.argv[1] + '| tee tmp')
with open('tmp') as f:
    last = None
    for last in (line for line in f if line.rstrip('\n')):
        pass
m = re.search('[0-9]\.[0-9]*', last)
if m:
    score = float(m.group(0))
else:
    print('Score not found')
    sys.exit(1)

if score < 7:
    print('A minimum pylint score of 7 is required')
    sys.exit(1)
else:
    sys.exit(0)

